version: "2"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql_conf:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
volumes:
  mysql-data:
    driver_opts:
      type: none
      device: /home/yterui/git_repos/project-t/mysql-docker-compose/mysql_data
      o: bind
